#!/bin/bash

# Replace the host entry for local host with IP, FQDN and Hostname
while read IP FQDN HOST SUBNET; do
    CMD="sudo -S sed -i 's/^127.0.1.1.*/127.0.1.1\t${FQDN} ${HOST}/' /etc/hosts"
    ssh -n jack@${IP} "$CMD"
    ssh -n jack@${IP} sudo -S hostnamectl set-hostname ${HOST}
    ssh -n jack@${IP} sudo -S systemctl restart systemd-hostnamed
done < machines
